# Machine Learning First Heading

## Task 1: Lists, Dictionaries, Tuples

### **Lists**

In [1]:
nums = [3,5,7,8,12]

In [2]:
cubes = []

In [3]:
for x in nums:
    item = x**3
    cubes.append(item)

In [4]:
print(cubes)

[27, 125, 343, 512, 1728]


In [5]:
nums.append(cubes)

In [6]:
print(nums)

[3, 5, 7, 8, 12, [27, 125, 343, 512, 1728]]


### **Dictionary**

In [7]:
dict = {}

In [8]:
dict["parrot"] = 2

In [9]:
dict["goat"] = 4

In [10]:
dict["spider"] = 8

In [11]:
dict["crab"] = 10

In [12]:
print(dict)

{'parrot': 2, 'goat': 4, 'spider': 8, 'crab': 10}


In [13]:
dictItems = dict.items()

In [14]:
print(dictItems)

dict_items([('parrot', 2), ('goat', 4), ('spider', 8), ('crab', 10)])


In [15]:
#for animal, legs in dict.items():
    #print(f"The {animal} has {legs}.")

In [16]:
#Sum of legs

In [17]:
total_legs = 0
for animal, legs in dict.items():
    print(f"The {animal} has {legs}.")
    total_legs += legs
print(f"Total Legs of all the animals: {total_legs}.")

The parrot has 2.
The goat has 4.
The spider has 8.
The crab has 10.
Total Legs of all the animals: 24.


### **Tuple**

In [18]:
A = (3,9,4,[5,6])   #tuples are immutable but we can the the array elements in because array are mutable

In [19]:
A[3][0] = 8

In [20]:
print(A)

(3, 9, 4, [8, 6])


In [21]:
del A

In [22]:
#print(A)

In [23]:
B = ("a", "p", "p", "l", "e")

In [24]:
B.count("p")

2

In [25]:
B.index("l")

3

## Task 2: Numpy

In [26]:
!pip install numpy

In [27]:
import numpy as np

In [28]:
A = ([1,2,3,4],[5,6,7,8],[9,10,11,12])

In [29]:
A_np = np.array(A) #Numpy Array

In [30]:
b = A_np[:2, 1:3]

In [31]:
print(b)

[[2 3]
 [6 7]]


In [32]:
# Empty matrix C with the same shape as A
C = np.empty(A_np.shape, dtype=int)
# C = np.zero(A_np.shape)

# Print matrix C
print(C)

[[4128860 6029375 3801155 5570652]
 [6619251 7536754 7143516 6815861]
 [7143521 4259932 7340144 6357060]]


In [33]:
z = np.array([1,0,1])

In [34]:
for col in range(A_np.shape[1]):
    C[:, col] = A_np[:, col] + z

In [37]:
print("Matrix A:")
print(A_np)

Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [36]:
print("Matrix C (A + z added to each column):")
print(C)

Matrix C (A + z added to each column):
[[ 2  3  4  5]
 [ 5  6  7  8]
 [10 11 12 13]]


In [38]:
#New Numpy Arrays

In [39]:
X = np.array([[1,2],[3,4]])
Y = np.array([[5,6],[7,8]])

In [40]:
v = np.array([9,10])

In [41]:
# Add matrices X and Y
sum_matrix = X + Y
print(f"Sum of matrices X and Y: {sum_matrix}")

Sum of matrices X and Y: [[ 6  8]
 [10 12]]


In [44]:
# Multiply matrices X and Y
product_matrix =  np.dot(X,Y)
print(product_matrix)

[[19 22]
 [43 50]]


In [50]:
# Compute the element-wise square root of matrix Y
sqrt_Y = np.sqrt(Y)
# sqrt_Y = np.floor(sqrt_Y).astype(int) #Round the Decimal values and then change the datatype to integer
print(f"Element-wise square root of matrix Y: {sqrt_Y}")

Element-wise square root of matrix Y: [[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [51]:
# Compute and print the dot product of the matrix X and vector v
dotProduct_Xv = np.dot(X,v)
print(f"Dot product of matrix X and v: {dotProduct_Xv}")

Dot product of matrix X and v: [29 67]


In [52]:
# Compute and print the sum of each column of X
sumX = np.sum(X, axis=0)
print(sumX)

[4 6]


In [53]:
# Compute and print the sum of each Row of X
np.sum(X, axis=1)
print(sumX)

[4 6]


## Task 3: Functions and Loops

In [54]:
#  Create a function ‘Compute’ that takes arguments, distance and time, calculate velocity
def Compute(d,t):
    v = d/t
    return v

In [55]:
distance = 500
time = 8
velocity = Compute(distance, time)
print(velocity)

62.5


In [59]:
# Even Numbers List
even_num = []
for num in range(13):
    if num%2 == 0:
        even_num.append(num)
print(even_num)

[0, 2, 4, 6, 8, 10, 12]


## Task 4: Pandas

In [60]:
pip install pandas

In [61]:
import pandas as pd

In [67]:
# Create a DataFrame
data = {
    'C1': [1,2,3,5,5],
    'C2': [6,7,5,4,8],
    'C3': [7,9,8,6,5],
    'C4': [7,5,2,8,8]
}

In [68]:
# print(data)
df = pd.DataFrame(data)
print(df)

   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [69]:
# Filtered DataFrame
filtered_df = df[df['C2'] > 6]
print("Filtered DataFrame (Age > 30):")
print(filtered_df)

Filtered DataFrame (Age > 30):
   C1  C2  C3  C4
1   2   7   9   5
4   5   8   5   8


In [70]:
# Print only the first two rows
print(df.head(2))

   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5


In [71]:
#  Print the second column.
print(df['C2'])

0    6
1    7
2    5
3    4
4    8
Name: C2, dtype: int64


In [83]:
#  Change the name of the third column from ‘C3’ to ‘B3’
df = df.rename(columns={'C3': 'B3'})
print(df)

   C1  C2  B3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [84]:
# Add a new column to the dataframe and name it ‘Sum’.
# Sum the entries of each row and add the result in the column ‘Sum’.
df['sum'] = df.sum(axis=1)

In [85]:
print(df)

   C1  C2  B3  C4  sum
0   1   6   7   7   21
1   2   7   9   5   23
2   3   5   8   2   18
3   5   4   6   8   23
4   5   8   5   8   26


In [92]:
# Read CSV file
path = r'C:\Users\muham\Downloads\hello_sample.csv'
df2 = pd.read_csv(path)
print(df2)

    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  September       66


In [93]:
print(df2.tail(2))

   Gender F_Color     B_Month  Weight
21   Male  Yellow       April      74
22   Male     Red  September       66


In [94]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Gender   23 non-null     object
 1   F_Color  23 non-null     object
 2   B_Month  23 non-null     object
 3   Weight   23 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 868.0+ bytes


In [95]:
print(df2.shape)  #Returns a tuple - first value shows the number of rows and the second value show the number of columns

(23, 4)


In [105]:
df_Sort = df2.sort_values(by= 'Weight')

In [106]:
print(df_Sort)

    Gender  F_Color     B_Month  Weight
2     Male    Black     October      53
16    Male    Black      August      54
9     Male     Blue         May      58
7   Female      Red   September      59
18    Male  Mustard   December       60
10  Female      Red    October       60
6     Male   Orange      August      60
8     Male     Blue        July      60
3   Female     Blue    February      63
11    Male    Black   September      65
22    Male      Red  September       66
20    Male    Black   February       67
13    Male    Black       April      72
1     Male      Red       March      72
21    Male   Yellow       April      74
19  Female    Black    October       76
0     Male    Black       March      77
4     Male    black    October       80
17    Male    Black     January      82
12    Male    Green    December      85
14    Male    Green    January       90
15    Male   Yellow   November       90
5   Female    Black    december      97


In [107]:
# To check for missing values
print(df.isnull())

    Gender  F_Color  B_Month  Weight
0    False    False    False   False
1    False    False    False   False
2    False    False    False   False
3    False    False    False   False
4    False    False    False   False
5    False    False    False   False
6    False    False    False   False
7    False    False    False   False
8    False    False    False   False
9    False    False    False   False
10   False    False    False   False
11   False    False    False   False
12   False    False    False   False
13   False    False    False   False
14   False    False    False   False
15   False    False    False   False
16   False    False    False   False
17   False    False    False   False
18   False    False    False   False
19   False    False    False   False
20   False    False    False   False
21   False    False    False   False
22   False    False    False   False


In [108]:
# To drop rows with missing values
df_dropped_rows = df.dropna()
print("DataFrame after dropping rows with missing values:")
print(df_dropped_rows)

DataFrame after dropping rows with missing values:
    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  Septembe

In [109]:
# To drop columns with missing values
df_dropped_columns = df.dropna(axis=1)
print("DataFrame after dropping columns with missing values:")
print(df_dropped_columns)

DataFrame after dropping columns with missing values:
    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  Septe